//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImageRFMVCCRUD.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBModels2 : DbContext
    {
        //public DBModels2()
        //    : base("name=DBModels2")
        //{
        //}

        public DBModels2()
            : base("Data Source=tcp:opgglobal.database.windows.net,1433;Initial Catalog=ImageRFDatabase;Persist Security Info=False;User ID=opgglobal;Password=OPG.Gl0bal;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;")
        {
        }


        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            //throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ImageRFTable> ImageRFTables { get; set; }
    }
}
